export const envKey = {
  SALT_ROUND: 'SALT_ROUND',
  TOKEN_EXPIRE_TIME: 'TOKEN_EXPIRE_TIME',
  REFRESH_TOKEN_EXPIRE_TIME: 'REFRESH_TOKEN_EXPIRE_TIME',
  ACCESS_TOKEN_SECRET_KEY: 'ACCESS_TOKEN_SECRET_KEY',
  REFRESH_TOKEN_SECRET_KEY: 'REFRESH_TOKEN_SECRET_KEY',
  FORGOT_PASSWORD_SECRET_KEY: 'FORGOT_PASSWORD_SECRET_KEY',
  FORGOT_PASSWORD_TOKEN_EXPIRE_TIME: 'FORGOT_PASSWORD_TOKEN_EXPIRE_TIME',
  FRONTEND_URL: 'FRONTEND_URL',
  VERIFY_EMAIL_SECRET_KEY: 'VERIFY_EMAIL_SECRET_KEY',
  VERIFY_EMAIL_TOKEN_EXPIRE_TIME: 'VERIFY_EMAIL_TOKEN_EXPIRE_TIME',
};
