export const envKey = {
  SALT_ROUND: 'SALT_ROUND',
  TOKEN_EXPIRE_TIME: 'TOKEN_EXPIRE_TIME',
  REFRESH_TOKEN_EXPIRE_TIME: 'REFRESH_TOKEN_EXPIRE_TIME',
  ACCESS_TOKEN_SECRET_KEY: 'ACCESS_TOKEN_SECRET_KEY',
  REFRESH_TOKEN_SECRET_KEY: 'REFRESH_TOKEN_SECRET_KEY',
};
